// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/harijar/geogame/internal/repo (interfaces: Countries)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_countries.go -package=mocks . Countries
//
// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	countries "github.com/harijar/geogame/internal/repo/postgres/countries"
	gomock "go.uber.org/mock/gomock"
)

// MockCountries is a mock of Countries interface.
type MockCountries struct {
	ctrl     *gomock.Controller
	recorder *MockCountriesMockRecorder
}

// MockCountriesMockRecorder is the mock recorder for MockCountries.
type MockCountriesMockRecorder struct {
	mock *MockCountries
}

// NewMockCountries creates a new mock instance.
func NewMockCountries(ctrl *gomock.Controller) *MockCountries {
	mock := &MockCountries{ctrl: ctrl}
	mock.recorder = &MockCountriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCountries) EXPECT() *MockCountriesMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCountries) Get(arg0 int) *countries.Country {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*countries.Country)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockCountriesMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCountries)(nil).Get), arg0)
}

// GetAnotherRandom mocks base method.
func (m *MockCountries) GetAnotherRandom(arg0 *countries.Country) *countries.Country {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnotherRandom", arg0)
	ret0, _ := ret[0].(*countries.Country)
	return ret0
}

// GetAnotherRandom indicates an expected call of GetAnotherRandom.
func (mr *MockCountriesMockRecorder) GetAnotherRandom(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnotherRandom", reflect.TypeOf((*MockCountries)(nil).GetAnotherRandom), arg0)
}

// GetCountriesCount mocks base method.
func (m *MockCountries) GetCountriesCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCountriesCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetCountriesCount indicates an expected call of GetCountriesCount.
func (mr *MockCountriesMockRecorder) GetCountriesCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCountriesCount", reflect.TypeOf((*MockCountries)(nil).GetCountriesCount))
}

// GetPlaceArea mocks base method.
func (m *MockCountries) GetPlaceArea(arg0 *countries.Country) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaceArea", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetPlaceArea indicates an expected call of GetPlaceArea.
func (mr *MockCountriesMockRecorder) GetPlaceArea(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaceArea", reflect.TypeOf((*MockCountries)(nil).GetPlaceArea), arg0)
}

// GetPlaceGDP mocks base method.
func (m *MockCountries) GetPlaceGDP(arg0 *countries.Country) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaceGDP", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetPlaceGDP indicates an expected call of GetPlaceGDP.
func (mr *MockCountriesMockRecorder) GetPlaceGDP(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaceGDP", reflect.TypeOf((*MockCountries)(nil).GetPlaceGDP), arg0)
}

// GetPlaceGDPPerCapita mocks base method.
func (m *MockCountries) GetPlaceGDPPerCapita(arg0 *countries.Country) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaceGDPPerCapita", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetPlaceGDPPerCapita indicates an expected call of GetPlaceGDPPerCapita.
func (mr *MockCountriesMockRecorder) GetPlaceGDPPerCapita(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaceGDPPerCapita", reflect.TypeOf((*MockCountries)(nil).GetPlaceGDPPerCapita), arg0)
}

// GetPlaceHDI mocks base method.
func (m *MockCountries) GetPlaceHDI(arg0 *countries.Country) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaceHDI", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetPlaceHDI indicates an expected call of GetPlaceHDI.
func (mr *MockCountriesMockRecorder) GetPlaceHDI(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaceHDI", reflect.TypeOf((*MockCountries)(nil).GetPlaceHDI), arg0)
}

// GetPlacePopulation mocks base method.
func (m *MockCountries) GetPlacePopulation(arg0 *countries.Country) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlacePopulation", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetPlacePopulation indicates an expected call of GetPlacePopulation.
func (mr *MockCountriesMockRecorder) GetPlacePopulation(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlacePopulation", reflect.TypeOf((*MockCountries)(nil).GetPlacePopulation), arg0)
}

// GetRandom mocks base method.
func (m *MockCountries) GetRandom() *countries.Country {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandom")
	ret0, _ := ret[0].(*countries.Country)
	return ret0
}

// GetRandom indicates an expected call of GetRandom.
func (mr *MockCountriesMockRecorder) GetRandom() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandom", reflect.TypeOf((*MockCountries)(nil).GetRandom))
}
