// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repo/repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/repo/repo.go -destination=internal/mocks/mock_countries.go -package=mocks
//
// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	countries "github.com/harijar/geogame/internal/repo/countries"
	gomock "go.uber.org/mock/gomock"
)

// MockCountries is a mock of Countries interface.
type MockCountries struct {
	ctrl     *gomock.Controller
	recorder *MockCountriesMockRecorder
}

// MockCountriesMockRecorder is the mock recorder for MockCountries.
type MockCountriesMockRecorder struct {
	mock *MockCountries
}

// NewMockCountries creates a new mock instance.
func NewMockCountries(ctrl *gomock.Controller) *MockCountries {
	mock := &MockCountries{ctrl: ctrl}
	mock.recorder = &MockCountriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCountries) EXPECT() *MockCountriesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCountries) Create(country *countries.Country) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", country)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCountriesMockRecorder) Create(country any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCountries)(nil).Create), country)
}

// Get mocks base method.
func (m *MockCountries) Get(id int) *countries.Country {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*countries.Country)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockCountriesMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCountries)(nil).Get), id)
}

// GetAnotherRandom mocks base method.
func (m *MockCountries) GetAnotherRandom(country *countries.Country) *countries.Country {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnotherRandom", country)
	ret0, _ := ret[0].(*countries.Country)
	return ret0
}

// GetAnotherRandom indicates an expected call of GetAnotherRandom.
func (mr *MockCountriesMockRecorder) GetAnotherRandom(country any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnotherRandom", reflect.TypeOf((*MockCountries)(nil).GetAnotherRandom), country)
}

// GetRandom mocks base method.
func (m *MockCountries) GetRandom() *countries.Country {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandom")
	ret0, _ := ret[0].(*countries.Country)
	return ret0
}

// GetRandom indicates an expected call of GetRandom.
func (mr *MockCountriesMockRecorder) GetRandom() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandom", reflect.TypeOf((*MockCountries)(nil).GetRandom))
}
